### ISSUE TITLE
ASTRAL issue

### ISSUE THREAD

**Issue by jiyideanjiao** [balabanmetin/uDance#4]
I used the "tree" option with backbone.nwk and the alignments of 12 genes including 2538 species. I always got error message "In cluster species/output/udance/3, 1 gene tree(s) with lower than 0.80 median lpp are discarded.
ASTRAL job on partition species/output/udance/3 has failed. Check the log file species/output/udance/3/astral.incremental.log for further information." 

When I check the astral.incremental.log file, it shows as below:

11 trees read from species/output/udance/3/astral_input.trees
All output trees will be *arbitrarily* rooted at species1232

Shutting down threading
Exception in thread "main" java.lang.RuntimeException: Error: Leptothorax_acervorum was not seen in main input trees.
	at phylonet.coalescent.TaxonIdentifier.taxonId(TaxonIdentifier.java:38)
	at phylonet.coalescent.CommandLine.readInputTrees(CommandLine.java:833)
	at phylonet.coalescent.CommandLine.runInference(CommandLine.java:639)
	at phylonet.coalescent.CommandLine.process(CommandLine.java:549)
	at phylonet.coalescent.CommandLineMP.process(CommandLineMP.java:194)
	at phylonet.coalescent.CommandLineMP.main(CommandLineMP.java:229)"

Do you have any idea to figure out this issue?

**Comment by balabanmetin** [comment]
A bad gene tree can occur due to failed or bad MSA or lack of phylogenetic signal in the gene.

**Comment by jiyideanjiao** [comment]
Get it. thanks very much!

**Comment by balabanmetin** [comment]
Is the issue resolved?

**Comment by jiyideanjiao** [comment]
still got error message at ASTRAL step
