### ISSUE TITLE
Error in `install.sh`

### ISSUE THREAD

**Issue by AroneyS** [balabanmetin/uDance#9]
The `install.sh` errors for me. Seems to be due to the treeshrink package from smirarab channel.

I guess the important bit is `HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/smirarab/linux-64/current_repodata.json` Though that link indeed doesn't work, https://conda.anaconda.org/smirarab/linux-64/repodata.json this one does exist.

```bash
Installing conda environment on Linux 64-bit platform
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/gateways/repodata/__init__.py", line 161, in conda_http_errors
        yield
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/gateways/repodata/__init__.py", line 127, in repodata
        response.raise_for_status()
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/smirarab/linux-64/current_repodata.json
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/requests/models.py", line 971, in json
        return complexjson.loads(self.text, **kwargs)
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/simplejson/__init__.py", line 514, in loads
        return _default_decoder.decode(s)
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/simplejson/decoder.py", line 386, in decode
        obj, end = self.raw_decode(s)
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/simplejson/decoder.py", line 416, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
        return getattr(module, func_name)(args, parser)
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/notices/core.py", line 121, in wrapper
        return func(*args, **kwargs)
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/cli/install.py", line 264, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/core/solve.py", line 134, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/core/solve.py", line 177, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/core/solve.py", line 282, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/core/solve.py", line 449, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/core/solve.py", line 1064, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/core/index.py", line 267, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/core/subdir_data.py", line 169, in query_all
        result = tuple(chain.from_iterable(executor.map(subdir_query, channel_urls)))
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
        yield fs.pop().result()
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/concurrent/futures/_base.py", line 437, in result
        return self.__get_result()
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
        raise self._exception
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/core/subdir_data.py", line 158, in subdir_query
        return tuple(
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/core/subdir_data.py", line 174, in query
        self.load()
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/core/subdir_data.py", line 264, in load
        _internal_state = self._load()
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/core/subdir_data.py", line 366, in _load
        raw_repodata_str = self._repo.repodata(cache.state)  # type: ignore
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/gateways/repodata/__init__.py", line 127, in repodata
        response.raise_for_status()
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/gateways/repodata/__init__.py", line 208, in conda_http_errors
        raise RepodataIsEmpty(
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/conda/exceptions.py", line 462, in __init__
        body = response.json()
      File "/mnt/hpccs01/work/microbiome/conda/lib/python3.8/site-packages/requests/models.py", line 975, in json
        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ /mnt/hpccs01/work/microbiome/conda/bin/conda create -y -c bioconda -c conda-forge --channel smirarab --name udance python=3.9 pip newick_utils=1.6 setuptools seqkit=2.1.0 scipy dendropy=4.5.2 pandas=1.3.0 snakemake raxml=8.2.12 iqtree=2.1.2 treeshrink=1.3.9 fasttree=2.1.10 julia=1.7.1 gappa=0.7.1 trimal=1.4.1 tqdist`
```

**Comment by AroneyS** [comment]
Switching to mamba in the `install.sh` script fixed the error.
